# Generated by Django 2.0.3 on 2018-04-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180418_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.CharField(max_length=255)),
                ('mark', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='students',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univ.Univ'),
        ),
    ]
