# Generated by Django 2.0.3 on 2018-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_attestat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='attestat',
        ),
        migrations.AddField(
            model_name='students',
            name='attestat',
            field=models.ManyToManyField(blank=True, null=True, to='students.Attestat'),
        ),
    ]
