# Generated by Django 2.0.3 on 2018-04-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180421_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='attestat',
        ),
        migrations.AddField(
            model_name='students',
            name='attestat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Attestat'),
        ),
    ]
