# Generated by Django 2.0.3 on 2018-04-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180422_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
