# Generated by Django 2.0.3 on 2018-04-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20180422_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestat2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.CharField(max_length=255)),
                ('mark', models.IntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Students')),
            ],
        ),
    ]
