# Generated by Django 2.0.3 on 2018-04-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_attestat2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestat2',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attestat2',
        ),
    ]
